simpledog_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

state_estimate_update:
  type: "balance_controller/StateEstimateController"
  real_robot: false
  use_gazebo_feedback: false
  joints: ['front_left_1_joint', 'front_left_2_joint', 'front_left_3_joint', 'front_right_1_joint', 'front_right_2_joint', 'front_right_3_joint', 'rear_right_1_joint', 'rear_right_2_joint', 'rear_right_3_joint', 'rear_left_1_joint', 'rear_left_2_joint', 'rear_left_3_joint']

single_leg_controller:
  type: "balance_controller/SingleLegController"
  joints: ['front_left_1_joint', 'front_left_2_joint', 'front_left_3_joint']
  legs: ['LF_LEG']
  control_methods: ['end_position']

base_balance_controller:
  type: "balance_controller/RosBalanceController"
  real_robot: false
  ignore_contact_sensor: false
  joints: ['front_left_1_joint', 'front_left_2_joint', 'front_left_3_joint', 'front_right_1_joint', 'front_right_2_joint', 'front_right_3_joint', 'rear_right_1_joint', 'rear_right_2_joint', 'rear_right_3_joint', 'rear_left_1_joint', 'rear_left_2_joint', 'rear_left_3_joint']
  front_left_1_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_left_2_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_left_3_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_right_1_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_right_2_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_right_3_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_left_1_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_left_2_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_left_3_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_right_1_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_right_2_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_right_3_joint/pid: {p: 300.0, i: 0.01, d: 3.0}

all_joints_position_effort_group_controller:
  type: effort_controllers/JointGroupPositionController
  joints: ['front_left_1_joint', 'front_left_2_joint', 'front_left_3_joint', 'front_right_1_joint', 'front_right_2_joint', 'front_right_3_joint', 'rear_right_1_joint', 'rear_right_2_joint', 'rear_right_3_joint', 'rear_left_1_joint', 'rear_left_2_joint', 'rear_left_3_joint']
  front_left_1_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_left_2_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_left_3_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_right_1_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_right_2_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_right_3_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_left_1_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_left_2_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_left_3_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_right_1_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_right_2_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_right_3_joint/pid: {p: 300.0, i: 0.01, d: 3.0}

all_joints_position_group_controller:
  type: position_controllers/JointGroupPositionController
  joints: ['front_left_1_joint', 'front_left_2_joint', 'front_left_3_joint', 'front_right_1_joint', 'front_right_2_joint', 'front_right_3_joint', 'rear_right_1_joint', 'rear_right_2_joint', 'rear_right_3_joint', 'rear_left_1_joint', 'rear_left_2_joint', 'rear_left_3_joint']
  front_left_1_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_left_2_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_left_3_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_right_1_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_right_2_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_right_3_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_left_1_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_left_2_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_left_3_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_right_1_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_right_2_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_right_3_joint/pid: {p: 300.0, i: 0.01, d: 3.0}

all_joints_velocity_group_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints: ['front_left_1_joint', 'front_left_2_joint', 'front_left_3_joint', 'front_right_1_joint', 'front_right_2_joint', 'front_right_3_joint', 'rear_right_1_joint', 'rear_right_2_joint', 'rear_right_3_joint', 'rear_left_1_joint', 'rear_left_2_joint', 'rear_left_3_joint']
  front_left_1_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_left_2_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_left_3_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_right_1_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_right_2_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_right_3_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_left_1_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_left_2_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_left_3_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_right_1_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_right_2_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_right_3_joint/pid: {p: 300.0, i: 0.01, d: 3.0}

all_joints_effort_group_controller:
  type: effort_controllers/JointGroupEffortController
  joints: ['front_left_1_joint', 'front_left_2_joint', 'front_left_3_joint', 'front_right_1_joint', 'front_right_2_joint', 'front_right_3_joint', 'rear_right_1_joint', 'rear_right_2_joint', 'rear_right_3_joint', 'rear_left_1_joint', 'rear_left_2_joint', 'rear_left_3_joint']
  front_left_1_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_left_2_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_left_3_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_right_1_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_right_2_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  front_right_3_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_left_1_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_left_2_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_left_3_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_right_1_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_right_2_joint/pid: {p: 300.0, i: 0.01, d: 3.0}
  rear_right_3_joint/pid: {p: 300.0, i: 0.01, d: 3.0}

front_left_1_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: front_left_1_joint
  pid: {p: 1000.0, i: 0.01, d: 10.0}

front_left_2_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: front_left_2_joint
  pid: {p: 1000.0, i: 0.01, d: 10.0}

front_left_3_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: front_left_3_joint
  pid: {p: 1000.0, i: 0.01, d: 10.0}

front_right_1_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: front_right_1_joint
  pid: {p: 1000.0, i: 0.01, d: 10.0}

front_right_2_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: front_right_2_joint
  pid: {p: 1000.0, i: 0.01, d: 10.0}

front_right_3_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: front_right_3_joint
  pid: {p: 1000.0, i: 0.01, d: 10.0}

rear_right_1_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: rear_right_1_joint
  pid: {p: 1000.0, i: 0.01, d: 10.0}

rear_right_2_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: rear_right_2_joint
  pid: {p: 1000.0, i: 0.01, d: 10.0}

rear_right_3_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: rear_right_3_joint
  pid: {p: 1000.0, i: 0.01, d: 10.0}

rear_left_1_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: rear_left_1_joint
  pid: {p: 1000.0, i: 0.01, d: 10.0}

rear_left_2_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: rear_left_2_joint
  pid: {p: 1000.0, i: 0.01, d: 10.0}

rear_left_3_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: rear_left_3_joint
  pid: {p: 1000.0, i: 0.01, d: 10.0}

Position_controller:
  type: balance_controller/balance_position_controller
  ignore_contact_sensor: false
  joints: ['front_left_1_joint', 'front_left_2_joint', 'front_left_3_joint', 'front_right_1_joint', 'front_right_2_joint', 'front_right_3_joint', 'rear_right_1_joint', 'rear_right_2_joint', 'rear_right_3_joint', 'rear_left_1_joint', 'rear_left_2_joint', 'rear_left_3_joint']

configure_change_controller:
  type: balance_controller/configure_change_controller
  ignore_contact_sensor: true
  joints: ['front_left_1_joint', 'front_left_2_joint', 'front_left_3_joint', 'front_right_1_joint', 'front_right_2_joint', 'front_right_3_joint', 'rear_right_1_joint', 'rear_right_2_joint', 'rear_right_3_joint', 'rear_left_1_joint', 'rear_left_2_joint', 'rear_left_3_joint']

walk_forward_controller:
  type: balance_controller/walk_forward_controller
  ignore_contact_sensor: true
  joints: ['front_left_1_joint', 'front_left_2_joint', 'front_left_3_joint', 'front_right_1_joint', 'front_right_2_joint', 'front_right_3_joint', 'rear_right_1_joint', 'rear_right_2_joint', 'rear_right_3_joint', 'rear_left_1_joint', 'rear_left_2_joint', 'rear_left_3_joint']
